### ISSUE TITLE
How to know that file already recorded and not in recording stage ? 

### ISSUE THREAD

**Issue by kovalroma** [qualitymanifest/timestampSDR#6]
Hello, maybe I am wrong but I found that timestampSDR works using the following algorithm.
When timestampSDR receives sound it creates file **somename.wav** and appends transmission based on timeout settings.  When timeout exceed it creates another file **somename2.wav** and appends transmission. 
I am writing tool for sync **somename.wav** with my storage. The idea is to search all *.wav in folder, sync them and delete.  How can i know that **somename.wav** is already recorded and not in process of recording. On my opinion good idea would be to write file with some other name **somename_in_process.wav** and after timeout exceeds rename to somename.wav. In this case I would exactly know which file is already recorded.

Or maybe there is some other method to find which file already recorded ?

**Comment by qualitymanifest** [comment]
As far as I know there isn't a way to tell if a file is currently being recorded, but it should be an easy change to prepend `RECORDING_` to in-progress file names. I'm pretty busy but I'll try to get around to it this week

**Comment by kovalroma** [comment]
It would be nice. For now I use dirty hack with ```lsof``` but to be honestly prepend ```RECORDING_``` is more elegant. Ideal is to add suffix ***.temp** or some other, something like **Jun-02-2020_15-32-31.wav.temp** and after file is recorded rename to ordinary **Jun-02-2020_15-32-31.wav** . IMHO suffix is much more better solution because it would be more easy to search already recorded files (grep with mask *.wav)

**Comment by qualitymanifest** [comment]
Implemented in e5a7ecf, I've barely tested it so let me know if you come across any issues
